INSERT INTO greeting (id, message) VALUES (1, 'Hello, Derby!');

INSERT INTO planets (id, name) VALUES (1, 'A');
INSERT INTO planets (id, name) VALUES (2, 'B');
INSERT INTO planets (id, name) VALUES (3, 'C');
INSERT INTO planets (id, name) VALUES (4, 'D');
INSERT INTO planets (id, name) VALUES (5, 'H');
INSERT INTO planets (id, name) VALUES (6, 'E');
INSERT INTO planets (id, name) VALUES (7, 'F');
INSERT INTO planets (id, name) VALUES (8, 'L');
INSERT INTO planets (id, name) VALUES (9, 'M');
INSERT INTO planets (id, name) VALUES (10, 'G');
INSERT INTO planets (id, name) VALUES (11, 'I');
INSERT INTO planets (id, name) VALUES (12, 'J');
INSERT INTO planets (id, name) VALUES (13, 'K');
INSERT INTO planets (id, name) VALUES (14, 'Z');
INSERT INTO planets (id, name) VALUES (15, 'T');
INSERT INTO planets (id, name) VALUES (16, 'N');
INSERT INTO planets (id, name) VALUES (17, 'S');
INSERT INTO planets (id, name) VALUES (18, 'O');
INSERT INTO planets (id, name) VALUES (19, 'U');
INSERT INTO planets (id, name) VALUES (20, 'R');
INSERT INTO planets (id, name) VALUES (21, 'P');
INSERT INTO planets (id, name) VALUES (22, 'L''');
INSERT INTO planets (id, name) VALUES (23, 'Y');
INSERT INTO planets (id, name) VALUES (24, 'Q');
INSERT INTO planets (id, name) VALUES (25, 'X');
INSERT INTO planets (id, name) VALUES (26, 'K''');
INSERT INTO planets (id, name) VALUES (27, 'J''');
INSERT INTO planets (id, name) VALUES (28, 'V');
INSERT INTO planets (id, name) VALUES (29, 'I''');
INSERT INTO planets (id, name) VALUES (30, 'A''');
INSERT INTO planets (id, name) VALUES (31, 'B''');
INSERT INTO planets (id, name) VALUES (32, 'C''');
INSERT INTO planets (id, name) VALUES (33, 'W');
INSERT INTO planets (id, name) VALUES (34, 'E''');
INSERT INTO planets (id, name) VALUES (35, 'D''');
INSERT INTO planets (id, name) VALUES (36, 'F''');
INSERT INTO planets (id, name) VALUES (37, 'G''');
INSERT INTO planets (id, name) VALUES (38, 'H''');

INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (1, 1, 2, 0.30);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (2, 1, 3, 0.90);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (3, 1, 4, 0.10);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (4, 2, 5, 0.20);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (5, 2, 6, 1.30);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (6, 3, 7, 0.30);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (7, 4, 8, 0.00);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (8, 4, 9, 0.20);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (9, 5, 10, 3.10);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (10, 6, 11, 6.10);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (11, 7, 12, 2.40);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (12, 7, 13, 0.30);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (13, 10, 14, 4.00);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (14, 11, 14, 3.70);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (15, 11, 12, 2.90);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (16, 8, 15, 9.80);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (17, 15, 16, 8.80);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (18, 15, 17, 13.40);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (19, 17, 18, 6.00);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (20, 18, 19, 3.50);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (21, 12, 20, 5.40);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (22, 20, 21, 1.90);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (23, 20, 22, 0.70);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (24, 14, 23, 3.20);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (25, 23, 24, 20.30);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (26, 24, 25, 10.40);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (27, 22, 25, 8.10);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (28, 25, 26, 0.70);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (29, 21, 19, 8.40);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (30, 19, 26, 12.30);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (31, 19, 27, 2.50);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (32, 27, 28, 3.00);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (33, 26, 28, 7.20);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (34, 27, 29, 13.40);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (35, 23, 30, 17.00);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (36, 30, 31, 7.20);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (37, 31, 32, 21.30);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (38, 26, 33, 16.00);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (39, 33, 32, 4.70);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (40, 33, 34, 33.90);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (41, 32, 35, 30.10);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (42, 34, 34, 7.60);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (43, 34, 36, 34.20);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (44, 36, 37, 2.40);
INSERT INTO routes (id, origin_planet_id, destination_planet_id, distance) VALUES (45, 37, 38, 1.10);
